# Generated by Django 4.0.1 on 2022-01-14 01:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imoveis',
            new_name='Imovel',
        ),
        migrations.RenameModel(
            old_name='Visitas',
            new_name='Visita',
        ),
    ]
